### ISSUE TITLE
Event Error

### ISSUE THREAD

**Issue by fatihege** [AktilaCengiz/proton-io#2]
Discord.js eğtiminde 2. sezon 3. bölüme geldim. Videoda "events" klasörüne "test.js" isminde bir modül oluşturuyorsun ve "node index.js" dediğinde sıkıntısız çalışıyor ama ben çalıştırmaya kalktığımda bir hata alıyor. Bu proton-io'dan kaynaklı bir sorun.

[Screenshot_1.png](https://imgupload.io/images/2021/02/22/Screenshot_1.png)

**Comment by AktilaCengiz** [comment]
**Selamlar Değerli Fatih Ege!**
Öncelikle eğitim setimi izlediğin için _çok teşekkür ederim_ fakat bunun bir **proton-io hatası olmadığını** üzülerek belirtiyorum.
Bahsettiğiniz **hatanın sebebi test.js** aslında **commands** yani komutlar klasöründe olmalıdır.
events klasöründe ise sadece olaylar yani **ready** vesaire gibi dosyalar olmalıdır. 
Videoyu daha dikkatli izlemeni tavsiye ederim.
O zaman commands klasörü içerisinde test.js oluşturduğumuzu daha iyi görebilirsin.

Ayrıca videodaki kodlara yine [buraya tıklayarak](https://github.com/AktilaCengiz/discord-bot-gelistirme-sezon-2) ulaşabilirsin.

Bize ulaştığın için teşekkür ederim.
Tekrardan iyi günler, iyi çalışmalar.
